-- Migration 027: Job Role Taxonomy (imported from Airtable)
-- 84 job roles with ~791 synonyms across 4 families
-- Source: Airtable base apptFYaQLMnZo1y3y, table tblCPr1CEvjIhLhHI

-- Create job_roles table
CREATE TABLE IF NOT EXISTS job_roles (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name        TEXT NOT NULL UNIQUE,
  family      TEXT NOT NULL,  -- Management | Technology | Core Engineering | Others
  synonyms    TEXT[] DEFAULT '{}',
  airtable_id TEXT,
  created_at  TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_job_roles_family ON job_roles(family);
CREATE INDEX IF NOT EXISTS idx_job_roles_name ON job_roles(name);

-- RLS: allow read for authenticated users
ALTER TABLE job_roles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "auth_read_job_roles" ON job_roles FOR SELECT TO authenticated USING (true);

-- Add job_role_id FK to jobs table for categorization during scraping
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS job_role_id UUID REFERENCES job_roles(id);
CREATE INDEX IF NOT EXISTS idx_jobs_job_role ON jobs(job_role_id);

-- Seed data: all job roles with synonyms
INSERT INTO job_roles (name, family, synonyms, airtable_id) VALUES ('Controls/Automation', 'Core Engineering', '{"Control & Automation Engineer", "Automation Engineer", "Control System Engineer", "Automation Specialist", "Automation Technician", "Controls Engineer", "Industrial Automation Engineer", "Controls Automation Lead", "Automation Control Engineer"}', 'recNB4yCjKidRiL4y') ON CONFLICT (name) DO NOTHING;
INSERT INTO job_roles (name, family, synonyms, airtable_id) VALUES ('Design/Manufacturing Engineer', 'Core Engineering', '{"Design Engineer", "Manufacturing Engineer", "Production Engineer", "Manufacturing Design Engineer", "Design and Production Engineer", "Mechanical Design Engineer", "Process Engineer", "Advanced Manufacturing Engineer", "Industrial Engineer"}', 'reczMuJICYyNjfXcq') ON CONFLICT (name) DO NOTHING;
INSERT INTO job_roles (name, family, synonyms, airtable_id) VALUES ('Maintenance Engineer', 'Core Engineering', '{"Maintenance Engineer", "Facilities Maintenance Engineer", "Mechanical Maintenance Engineer", "Building Maintenance Engineer", "Facility Maintenance Engineer", "Maintenance Engineering Specialist", "Service Operation Engineer Maintenance", "Assistant Manager Maintenance", "Operations & Maintenance Engineer"}', 'rec8O6yod707Aanut') ON CONFLICT (name) DO NOTHING;
INSERT INTO job_roles (name, family, synonyms, airtable_id) VALUES ('Quantity Surveying Assistant', 'Core Engineering', '{"Assistant Quantity Surveyor", "Junior Quantity Surveyor", "Trainee Quantity Surveyor", "Quantity Surveyor Assistant", "Quantity Surveying Technician", "QS Assistant"}', 'recpcuzQ9qR3qPiSv') ON CONFLICT (name) DO NOTHING;
INSERT INTO job_roles (name, family, synonyms, airtable_id) VALUES ('R&D Tech', 'Core Engineering', '{"Research and Development Engineer", "R&D Technician", "R&D Technologist", "R&D Manager", "Research and Development Specialist", "R&D Expert", "Research Services Manager", "Product Development Engineer", "Food Technologist", "Technology Innovation Architect"}', 'recySabALfUdRcDhl') ON CONFLICT (name) DO NOTHING;
INSERT INTO job_roles (name, family, synonyms, airtable_id) VALUES ('Site/Project Engineer', 'Core Engineering', '{"Project Engineer", "Site Engineer", "Civil Site Engineer", "Civil Engineer", "Construction Engineer", "Project Coordinator", "Resident Engineer", "Project Manager", "Site Supervisor", "Civil Project Engineer"}', 'recqk5T3D3nrvemSF') ON CONFLICT (name) DO NOTHING;
INSERT INTO job_roles (name, family, synonyms, airtable_id) VALUES ('Structural/Design Engineer', 'Core Engineering', '{"Structural Design Engineer", "Structural Engineer", "Senior Structural Engineer", "Structural Designer", "Civil Structural Engineer", "Structure Design Engineer", "Project Engineer"}', 'rec8m3qIRRDg7quNH') ON CONFLICT (name) DO NOTHING;
INSERT INTO job_roles (name, family, synonyms, airtable_id) VALUES ('APM', 'Management', '{"APM Support Specialist", "Senior Business Analyst APM", "Senior Technology Engineer APM", "Store Manager APM", "Vice President APM", "Head of Portfolio APM", "Senior Principal Solution Consultant APM"}', 'recTXV1Ihjk3dCz8J') ON CONFLICT (name) DO NOTHING;
INSERT INTO job_roles (name, family, synonyms, airtable_id) VALUES ('Account Executive', 'Management', '{"Account Executive", "Accounts Executive", "Sales Executive", "Account Manager", "Channel Account Executive", "Enterprise Account Executive", "Accounts & Audit Executive", "Administration and Accounts Executive"}', 'reccagOs92I36j20k') ON CONFLICT (name) DO NOTHING;
INSERT INTO job_roles (name, family, synonyms, airtable_id) VALUES ('Audit/Assurance', 'Management', '{"Audit Manager", "Internal Auditor", "External Auditor", "Senior Auditor", "Audit Associate", "Assurance Associate", "Audit Senior", "Assistant Manager Audit", "Audit & Assurance Executive", "Quality Assurance Manager", "Audit Supervisor", "Audit Consultant", "Audit Officer", "Audit & Assurance Manager"}', 'rec07AbdirxeCPHFB') ON CONFLICT (name) DO NOTHING;
INSERT INTO job_roles (name, family, synonyms, airtable_id) VALUES ('BDE', 'Management', '{"Business Development Executive", "Business Development Manager", "Sales Executive", "Sales Manager", "Account Manager", "Business Development Officer", "Sales Representative", "Client Relationship Manager", "Key Account Manager"}', 'recDELf45wdllUEeK') ON CONFLICT (name) DO NOTHING;
INSERT INTO job_roles (name, family, synonyms, airtable_id) VALUES ('BI Analyst', 'Management', '{"Business Intelligence Analyst", "BI Analyst", "Data Analyst", "Business Analyst", "Business Intelligence Developer", "Power BI Developer", "Business Intelligence Consultant"}', 'recKev8qOa9lzr9zV') ON CONFLICT (name) DO NOTHING;
INSERT INTO job_roles (name, family, synonyms, airtable_id) VALUES ('Behaviour Analyst (entry)', 'Management', '{"Behaviour Analyst", "Board Certified Behavior Analyst (BCBA)", "Applied Behaviour Analyst", "ABA Therapist", "Behavioral Therapist", "ABA Technician", "Behavior Therapist"}', 'rec79lgqtvLv7PKEi') ON CONFLICT (name) DO NOTHING;
INSERT INTO job_roles (name, family, synonyms, airtable_id) VALUES ('Brand Manager', 'Management', '{"Brand Manager", "Assistant Brand Manager", "Brand Marketing Manager", "Brand Development Manager", "Brand Experience Manager", "Brand Lead", "Brand Executive", "Brand Strategist", "Brand Ambassador", "Product Manager"}', 'recfRMuewJ0q5Fll8') ON CONFLICT (name) DO NOTHING;
INSERT INTO job_roles (name, family, synonyms, airtable_id) VALUES ('Business Analyst (Product)', 'Management', '{"Business Analyst", "Product Analyst", "Product Owner", "Product Manager", "Business Analyst - Product", "Business Analyst - Digital Product", "Business Analyst - Product Management", "Senior Business Analyst", "IT Business Analyst", "Functional Business Analyst", "Business Systems Analyst", "Business Consultant"}', 'rec0iJyJsnCWzXrak') ON CONFLICT (name) DO NOTHING;
INSERT INTO job_roles (name, family, synonyms, airtable_id) VALUES ('Business Manager', 'Management', '{"Business Manager", "Business Development Manager", "General Manager", "Operations Manager", "Business Director", "Sales Manager", "Senior Manager", "Account Manager", "Partnership & Business Development Manager", "Business Development Executive"}', 'recBjgMJrRhOYyPj8') ON CONFLICT (name) DO NOTHING;
INSERT INTO job_roles (name, family, synonyms, airtable_id) VALUES ('CRM/Retention', 'Management', '{"CRM Manager", "Retention Specialist", "CRM Specialist", "Customer Retention Specialist", "CRM Executive", "CRM & Sales Support Coordinator", "Client Relationship Executive", "Customer Relationship Manager", "Customer Retention Manager", "CRM and Retention Manager"}', 'rect0LPC9ZIYtqKO7') ON CONFLICT (name) DO NOTHING;
INSERT INTO job_roles (name, family, synonyms, airtable_id) VALUES ('Compensation & Benefits', 'Management', '{"Compensation & Benefits Manager", "Compensation & Benefits Specialist", "Compensation & Benefits Analyst", "Compensation & Benefits Executive", "Compensation & Benefits Officer", "Compensation & Benefits Consultant", "Total Rewards Manager", "Total Rewards Specialist", "Benefits & Compensation Manager", "Benefits & Compensation Specialist", "Compensation & Benefits Intern"}', 'recvkSm6A2bVeq61g') ON CONFLICT (name) DO NOTHING;
INSERT INTO job_roles (name, family, synonyms, airtable_id) VALUES ('Customer Success Manager', 'Management', '{"Customer Success Manager", "Senior Customer Success Manager", "Customer Success Lead", "Client Success Manager", "Customer Success Director", "Customer Success Operations Manager", "Customer Success Representative", "Onboarding Manager"}', 'rechKtLe4SQS6AOSS') ON CONFLICT (name) DO NOTHING;
INSERT INTO job_roles (name, family, synonyms, airtable_id) VALUES ('Data Analyst', 'Management', '{"Data Analyst", "Business Analyst", "Data Scientist", "Business Intelligence Analyst", "Research Analyst", "Data Engineer", "Reporting Analyst", "Data Specialist", "Data Consultant", "Data Analytics Specialist", "Data Insights Analyst", "Data Visualization Analyst"}', 'reczol0HNKAnz6dOg') ON CONFLICT (name) DO NOTHING;
INSERT INTO job_roles (name, family, synonyms, airtable_id) VALUES ('Digital Marketer', 'Management', '{"Digital Marketing Manager", "Digital Marketing Executive", "Digital Marketing Specialist", "Social Media Manager", "Digital Marketer", "Digital Marketing Coordinator", "Performance Marketing Manager", "Social Media Executive", "Digital Marketing Analyst", "Digital Marketing Consultant", "Social Media Specialist", "Digital Content Manager", "Digital Campaign Manager", "Online Marketing Manager", "Digital Media Manager"}', 'rec9Dl9w3vLSqjyWm') ON CONFLICT (name) DO NOTHING;
INSERT INTO job_roles (name, family, synonyms, airtable_id) VALUES ('FP&A', 'Management', '{"Financial Planning and Analysis Manager", "FP&A Manager", "Financial Planning and Analysis Analyst", "FP&A Analyst", "Senior Manager FP&A", "Associate Director FP&A", "Finance Manager", "Financial Analyst", "Financial Planning and Reporting Manager", "Financial Planning & Analysis Director"}', 'rec38RDwkWKfldn7n') ON CONFLICT (name) DO NOTHING;
INSERT INTO job_roles (name, family, synonyms, airtable_id) VALUES ('FinTech Ops', 'Management', '{"Chief Operating Officer", "Fintech Operations Leader", "Head of Operations Fintech", "Operations Director", "Fintech IT Administrator", "Fintech Digital Project Lead", "Technical Project Manager Fintech"}', 'recGGOrbT8xO08xfQ') ON CONFLICT (name) DO NOTHING;
INSERT INTO job_roles (name, family, synonyms, airtable_id) VALUES ('Financial Analyst', 'Management', '{"Financial Analyst", "Senior Financial Analyst", "Finance Analyst", "FP&A Analyst", "Financial Planning and Analysis Analyst", "Financial Reporting Analyst", "Business Finance Analyst", "Corporate Finance Analyst", "Commercial Finance Analyst", "Budget Analyst", "Cost Analyst", "Investment Analyst", "Equity Analyst", "Financial Business Analyst"}', 'recnInNh2sWbcVqRc') ON CONFLICT (name) DO NOTHING;
INSERT INTO job_roles (name, family, synonyms, airtable_id) VALUES ('Founder/Operator', 'Management', '{"Founder", "Owner", "Co-Founder", "Owner Operator", "Managing Director", "Chief Executive Officer", "Business Owner", "Entrepreneur"}', 'recG1sLFgDBWSVRqa') ON CONFLICT (name) DO NOTHING;
INSERT INTO job_roles (name, family, synonyms, airtable_id) VALUES ('HR Analytics (I/O lens)', 'Management', '{"HR Analytics Manager", "HR Data Analyst", "HR Analyst", "People Analytics Manager", "HR Analytics Specialist", "HR Reporting Analyst", "HR Business Analyst", "HR Insights Analyst", "People Data Analyst", "Workforce Analytics Manager"}', 'recPFDFePoeQAxJfo') ON CONFLICT (name) DO NOTHING;
INSERT INTO job_roles (name, family, synonyms, airtable_id) VALUES ('HR Generalist', 'Management', '{"HR Generalist", "Human Resources Generalist", "HR Executive", "HR Officer", "HR Specialist", "HR Administrator", "Senior HR Generalist", "People Operations Specialist"}', 'recKMrCZMyIVlW69X') ON CONFLICT (name) DO NOTHING;
INSERT INTO job_roles (name, family, synonyms, airtable_id) VALUES ('HRBP', 'Management', '{"HR Business Partner", "HRBP", "Senior HR Business Partner", "HR Manager", "Human Resources Business Partner", "Manager – HRBP", "People Strategy Manager"}', 'recy0bddIqeApfIiC') ON CONFLICT (name) DO NOTHING;
INSERT INTO job_roles (name, family, synonyms, airtable_id) VALUES ('L&D', 'Management', '{"Learning and Development Manager", "L&D Manager", "Learning and Development Specialist", "L&D Specialist", "Learning and Development Lead", "L&D Lead", "Learning and Development Trainer", "L&D Trainer", "Learning and Development Coordinator", "L&D Coordinator", "Learning and Development Officer", "L&D Officer", "Learning and Development Consultant", "L&D Consultant"}', 'rec1XUqTRJ0EJENj2') ON CONFLICT (name) DO NOTHING;
INSERT INTO job_roles (name, family, synonyms, airtable_id) VALUES ('Logistics Coordinator', 'Management', '{"Logistics Coordinator", "Operations Coordinator", "Supply Chain Coordinator", "Logistics Officer", "Logistics Executive", "Shipping Coordinator", "Import Export Coordinator", "Warehouse Coordinator", "Transport Coordinator", "Freight Coordinator"}', 'rec4YrRLLUk0Ot8mf') ON CONFLICT (name) DO NOTHING;
INSERT INTO job_roles (name, family, synonyms, airtable_id) VALUES ('Management Trainee', 'Management', '{"Management Trainee", "Graduate Trainee", "Management Associate", "Graduate Program Associate", "Trainee Manager", "Future Leader Program", "Leadership Development Program"}', 'recht37A1m05WMm1O') ON CONFLICT (name) DO NOTHING;
INSERT INTO job_roles (name, family, synonyms, airtable_id) VALUES ('Operations Analyst', 'Management', '{"Operations Analyst", "Business Operations Analyst", "Treasury Operations Analyst", "Payment Operations Analyst", "Operations Associate", "Operations Coordinator", "Operations Specialist"}', 'recSB7db8ysHuQbv0') ON CONFLICT (name) DO NOTHING;
INSERT INTO job_roles (name, family, synonyms, airtable_id) VALUES ('PMO Analyst', 'Management', '{"PMO Analyst", "PMO Specialist", "Portfolio Management Office Analyst", "Project Management Office Analyst", "PMO Coordinator", "PMO Officer", "Project Analyst", "Project Coordinator"}', 'recbvEaJzx8GpPlaP') ON CONFLICT (name) DO NOTHING;
INSERT INTO job_roles (name, family, synonyms, airtable_id) VALUES ('Partner Manager', 'Management', '{"Partner Manager", "Partnership Manager", "Partnerships Manager", "Channel Partner Manager", "Business Development Manager", "Managing Partner", "Strategic Partnerships Manager", "Alliance Manager", "Channel Manager"}', 'recCwX8TwaDvEh40u') ON CONFLICT (name) DO NOTHING;
INSERT INTO job_roles (name, family, synonyms, airtable_id) VALUES ('Performance Marketer', 'Management', '{"Performance Marketing Manager", "Performance Marketing Executive", "Performance Marketing Specialist", "Performance Marketer", "Media Performance Manager", "Digital Performance Marketing Manager", "Senior Performance Marketing Manager", "Regional Performance Marketing Lead"}', 'recPU1Cpmc8YZX3wb') ON CONFLICT (name) DO NOTHING;
INSERT INTO job_roles (name, family, synonyms, airtable_id) VALUES ('Procurement Specialist', 'Management', '{"Procurement Specialist", "Procurement Officer", "Purchasing Specialist", "Purchasing Officer", "Procurement Executive", "Procurement Coordinator", "Procurement Manager", "Sourcing Specialist", "Buyer", "Purchasing Executive"}', 'recP08CxSYS02Y7mk') ON CONFLICT (name) DO NOTHING;
INSERT INTO job_roles (name, family, synonyms, airtable_id) VALUES ('Product Ops', 'Management', '{"Product Operations Manager", "Product Operations Lead", "Product Strategy Operations Manager", "Product Operations Specialist", "Product Operations Analyst", "Product Manager", "Product Strategy Manager"}', 'recyJXob3o6OruA8f') ON CONFLICT (name) DO NOTHING;
INSERT INTO job_roles (name, family, synonyms, airtable_id) VALUES ('Project Coordinator', 'Management', '{"Project Coordinator", "Project Administrator", "Project Officer", "Project Support Officer", "Project Assistant", "Project Management Coordinator", "Project Support Coordinator", "Project Control Coordinator", "Project Scheduler", "Project Executive"}', 'recsnGCyOkUOkuMpZ') ON CONFLICT (name) DO NOTHING;
INSERT INTO job_roles (name, family, synonyms, airtable_id) VALUES ('Research Assistant', 'Management', '{"Research Assistant", "Research Associate", "Medical Research Assistant", "Clinical Research Assistant", "Laboratory Assistant", "Academic Research Assistant", "Scientific Research Assistant"}', 'recKThry9EvOde7hf') ON CONFLICT (name) DO NOTHING;
INSERT INTO job_roles (name, family, synonyms, airtable_id) VALUES ('SCM Planner', 'Management', '{"Supply Chain Planner", "Supply Chain Coordinator", "Supply Chain Specialist", "Supply Chain Planning Specialist", "Demand Planner", "Planning Specialist Supply Chain Management", "Supply Chain Analyst", "Supply Chain Management Planner"}', 'recLKjCaiktL12TmL') ON CONFLICT (name) DO NOTHING;
INSERT INTO job_roles (name, family, synonyms, airtable_id) VALUES ('SEO/Content', 'Management', '{"SEO Specialist", "SEO Content Writer", "SEO Manager", "Digital Marketing Specialist", "SEO Content Operator", "SEO Analyst", "SEO Lead", "Content Writer", "Content Specialist", "SEO Marketing Manager", "Senior SEO Specialist", "Copywriter"}', 'rec9vaSTwQR9tnuLQ') ON CONFLICT (name) DO NOTHING;
INSERT INTO job_roles (name, family, synonyms, airtable_id) VALUES ('Scrum Master', 'Management', '{"Scrum Master", "Agile Coach", "Project Manager", "Agile Scrum Master", "Iteration Manager", "Team Coach"}', 'rec2Eo0CdLdpTy2GZ') ON CONFLICT (name) DO NOTHING;
INSERT INTO job_roles (name, family, synonyms, airtable_id) VALUES ('Strategy Analyst', 'Management', '{"Strategy Analyst", "Strategic Analyst", "Business Strategy Analyst", "Corporate Strategy Analyst", "Strategy Consultant", "Strategy Associate", "Strategy and Planning Analyst", "Strategy Planning Analyst", "Management Consultant"}', 'recucN4oyS3us2unF') ON CONFLICT (name) DO NOTHING;
INSERT INTO job_roles (name, family, synonyms, airtable_id) VALUES ('Talent Acquisition', 'Management', '{"Talent Acquisition Specialist", "Talent Acquisition Manager", "Talent Acquisition Officer", "Senior Talent Acquisition Specialist", "Recruitment Specialist", "Talent Acquisition Partner", "Talent Acquisition Consultant", "Recruitment Manager", "Talent Partner", "Hiring Specialist"}', 'recA6ShwF6BJdqgEE') ON CONFLICT (name) DO NOTHING;
INSERT INTO job_roles (name, family, synonyms, airtable_id) VALUES ('Treasury/Corporate Finance', 'Management', '{"Head of Finance", "Group Finance Manager", "Treasury Manager", "Treasury Analyst", "Treasury Operations Analyst", "Senior Associate Treasury", "Corporate Finance Manager", "Financial Controller", "Treasury Management Analyst", "Assistant Treasurer", "Cash Manager", "Treasury Governance Manager", "Treasury Senior Associate", "Treasury Operations Manager"}', 'reccaTxw6jjCeRyMU') ON CONFLICT (name) DO NOTHING;
INSERT INTO job_roles (name, family, synonyms, airtable_id) VALUES ('Academic Researcher (aligned to chosen discipline)', 'Others', '{"Academic Researcher", "Researcher", "Research Assistant", "Postdoctoral Researcher", "Research Fellow", "Research Associate", "Lecturer", "Assistant Professor", "Associate Professor", "Professor"}', 'recDjaUbRXmGW2FdN') ON CONFLICT (name) DO NOTHING;
INSERT INTO job_roles (name, family, synonyms, airtable_id) VALUES ('Academic Support', 'Others', '{"Academic Advisor", "Academic Support Officer", "Academic Assistant", "Senior Specialist Academic Support", "Academic Support Specialist", "Student Support Officer", "Academic Coordinator"}', 'recyISHSrYIfAwkPk') ON CONFLICT (name) DO NOTHING;
INSERT INTO job_roles (name, family, synonyms, airtable_id) VALUES ('Clinical Educator (junior)', 'Others', '{"Clinical Educator", "Clinical Nurse Educator", "Nurse Educator", "Clinical Instructor", "Medical Educator", "Health Educator", "Clinical Resource Nurse", "Clinical Pharmacy Instructor", "Clinical Education Specialist"}', 'recQOkSzz3Bv7MsQa') ON CONFLICT (name) DO NOTHING;
INSERT INTO job_roles (name, family, synonyms, airtable_id) VALUES ('Content Design', 'Others', '{"Content Designer", "Content Design Manager", "Content Creator", "Content Strategist", "UX Writer", "Digital Content Specialist", "Content Editor", "Copywriter", "Content Manager", "Digital Content Manager"}', 'recVE8DjEoy473TG1') ON CONFLICT (name) DO NOTHING;
INSERT INTO job_roles (name, family, synonyms, airtable_id) VALUES ('Content Design)', 'Others', '{"Content Designer", "Content Design Lead", "Content Strategist", "Content Producer", "Digital Content Designer", "Content Director", "Content Creator", "UX Writer", "Content Marketing Specialist", "Content Manager"}', 'recEwVfc0BXMn1SSR') ON CONFLICT (name) DO NOTHING;
INSERT INTO job_roles (name, family, synonyms, airtable_id) VALUES ('Copy/Content Writer', 'Others', '{"Copywriter", "Content Writer", "Content Creator", "Content Developer", "SEO Content Writer", "Digital Content Writer", "Arabic Content Writer", "UX Writer", "Content Specialist", "Content Editor", "Copy Editor", "Creative Writer", "Social Media Content Writer", "English Content Writer"}', 'recoIUTUl772IBMox') ON CONFLICT (name) DO NOTHING;
INSERT INTO job_roles (name, family, synonyms, airtable_id) VALUES ('Corporate Comms', 'Others', '{"Corporate Communications Manager", "Corporate Communications Executive", "Head of Corporate Communications", "Director of Corporate Communications", "Communications Manager", "Communications Executive", "Communications Director", "PR Manager", "Media Relations Manager", "Corporate Affairs Manager", "Corporate Affairs Director", "Corporate Brand and Communications Coordinator", "Investor Relations Specialist"}', 'recrMcCzRGXYveDG0') ON CONFLICT (name) DO NOTHING;
INSERT INTO job_roles (name, family, synonyms, airtable_id) VALUES ('Instructional Designer (junior)', 'Others', '{"Instructional Designer", "Junior Instructional Designer", "Learning Designer", "Learning and Development Specialist", "Instructional Design Specialist", "Training Specialist", "E-learning Designer", "Learning Specialist"}', 'rec3TeaLN1dX6RrJV') ON CONFLICT (name) DO NOTHING;
INSERT INTO job_roles (name, family, synonyms, airtable_id) VALUES ('Motion/Video', 'Others', '{"Motion Graphics Designer", "Video Editor", "Motion Designer", "Motion Graphics Artist", "Videographer", "Motion Graphics Animator", "Motion Graphics Editor", "Video Maker"}', 'recFzEx92DCvfPOjF') ON CONFLICT (name) DO NOTHING;
INSERT INTO job_roles (name, family, synonyms, airtable_id) VALUES ('PR Exec', 'Others', '{"PR Executive", "Public Relations Executive", "Public Relations Officer", "PR Officer", "PR Account Executive", "Communications Executive", "Public Relations Coordinator", "Senior PR Executive", "Marketing Public Relations Executive", "Social Media Executive"}', 'recdayUNiOOyg89Xy') ON CONFLICT (name) DO NOTHING;
INSERT INTO job_roles (name, family, synonyms, airtable_id) VALUES ('Quality & Patient Safety Assistant', 'Others', '{"Quality and Patient Safety Assistant", "Patient Safety Assistant", "Quality Assistant", "Patient Safety & Quality Officer", "Quality and Patient Safety Officer", "Healthcare Quality Assistant", "Quality Officer", "Patient Safety Officer", "Patient Care Assistant", "Healthcare Assistant"}', 'recSoClmyeEFiAiEC') ON CONFLICT (name) DO NOTHING;
INSERT INTO job_roles (name, family, synonyms, airtable_id) VALUES ('Screen/Media Content Creator (mapped via Motion/Video', 'Others', '{"Content Creator", "Social Media Content Creator", "Video Content Creator", "Digital Content Creator", "Social Media Manager", "Videographer", "Motion Graphics Designer", "Media Content Creator", "Visual Content Creator", "Multimedia Content Creator"}', 'recFdG3TwI4D2bwMF') ON CONFLICT (name) DO NOTHING;
INSERT INTO job_roles (name, family, synonyms, airtable_id) VALUES ('Social Media Manager', 'Others', '{"Social Media Manager", "Social Media Executive", "Social Media Specialist", "Social Media Marketing Manager", "Digital Marketing Manager", "Social Media Content Creator", "Senior Social Media Manager", "Social Media Lead", "Social Media Coordinator", "Social Media Strategist"}', 'recFeLGoZLPDDW9nh') ON CONFLICT (name) DO NOTHING;
INSERT INTO job_roles (name, family, synonyms, airtable_id) VALUES ('Staff Nurse', 'Others', '{"Staff Nurse", "Registered Nurse", "Senior Staff Nurse", "Nurse", "Home Care Nurse", "Site Nurse", "Practice Nurse"}', 'recN74e0GBuGbuIaT') ON CONFLICT (name) DO NOTHING;
INSERT INTO job_roles (name, family, synonyms, airtable_id) VALUES ('Teacher/Educator (PG pathways)', 'Others', '{"Teacher", "Educator", "Primary Teacher", "Homeroom Teacher", "Early Childhood Teacher", "Elementary Teacher", "Humanities Teacher", "Subject Teacher", "Classroom Teacher", "Special Education Teacher", "Learning Support Teacher", "Academic Instructor", "PGCE Teacher", "International School Teacher", "IB Teacher", "Curriculum Coordinator"}', 'rec9bTuS8sgsowH7E') ON CONFLICT (name) DO NOTHING;
INSERT INTO job_roles (name, family, synonyms, airtable_id) VALUES ('UI/UX Designer', 'Others', '{"UI/UX Designer", "UX Designer", "UI Designer", "Product Designer", "UX/UI Designer", "Web & Graphic Designer", "Senior UI/UX Designer", "Head of Creative & UX", "User Experience Designer", "Digital Product Designer"}', 'recAH4EVXtDm8VNzW') ON CONFLICT (name) DO NOTHING;
INSERT INTO job_roles (name, family, synonyms, airtable_id) VALUES ('Visual/Communication Designer', 'Others', '{"Graphic Designer", "Visual Designer", "Communication Designer", "Brand Designer", "Creative Designer", "Art Director", "Senior Graphic Designer", "Digital Designer", "Visual Communication Designer", "Visual Communication Specialist", "Visual Content Designer", "Visual Arts Designer", "Multimedia Designer", "UI Designer", "Visual Merchandiser"}', 'rec7lz7DyAfu0BwDv') ON CONFLICT (name) DO NOTHING;
INSERT INTO job_roles (name, family, synonyms, airtable_id) VALUES ('Backend Engineer', 'Technology', '{"Backend Developer", "Backend Engineer", "Back End Developer", "Back End Engineer", "Backend Software Engineer", "Java Backend Engineer", "Python Backend Engineer", "Software Engineer"}', 'rec1KqhWQdjiKGaJ5') ON CONFLICT (name) DO NOTHING;
INSERT INTO job_roles (name, family, synonyms, airtable_id) VALUES ('Cloud/Systems Admin', 'Technology', '{"Cloud Administrator", "System Administrator", "IT System Administrator", "Systems Administrator", "Cloud Engineer", "Cloud Systems Administrator", "IT Administrator", "Server & System Administrator", "Network & Systems Administrator"}', 'recfbMUruPMSOfUE0') ON CONFLICT (name) DO NOTHING;
INSERT INTO job_roles (name, family, synonyms, airtable_id) VALUES ('Controls/Systems Eng', 'Technology', '{"Control Systems Engineer", "Controls Engineer", "Control Engineer", "Automation Engineer", "Instrumentation and Control Engineer", "Electrical and Controls Engineer", "Lead Control Systems Engineer", "DCS Engineer", "SCADA Engineer", "PLC Engineer", "Process Control Engineer"}', 'recJCWmb9r14Auq0v') ON CONFLICT (name) DO NOTHING;
INSERT INTO job_roles (name, family, synonyms, airtable_id) VALUES ('Data Scientist (entry)', 'Technology', '{"Data Scientist", "Junior Data Scientist", "Data Analyst", "Data Science Associate", "Graduate Data Scientist", "Entry Level Data Scientist", "Junior Data Analyst", "Data Science Intern", "Associate Data Scientist"}', 'recjiybRATisG95Aw') ON CONFLICT (name) DO NOTHING;
INSERT INTO job_roles (name, family, synonyms, airtable_id) VALUES ('DevOps Engineer', 'Technology', '{"DevOps Engineer", "Senior DevOps Engineer", "DevOps Lead", "DevOps Architect", "Cloud DevOps Engineer", "AWS DevOps Engineer", "Azure DevOps Engineer", "Site Reliability Engineer", "DevOps Specialist", "DevOps Consultant"}', 'rec4qDDunKGRjrmN3') ON CONFLICT (name) DO NOTHING;
INSERT INTO job_roles (name, family, synonyms, airtable_id) VALUES ('Embedded Systems Eng (junior)', 'Technology', '{"Junior Embedded Systems Engineer", "Embedded Systems Engineer", "Embedded Software Engineer", "Embedded Software Developer", "Embedded AI Engineer", "Embedded IoT Engineer", "Embedded C Developer"}', 'recShJWsdSZQbfVyP') ON CONFLICT (name) DO NOTHING;
INSERT INTO job_roles (name, family, synonyms, airtable_id) VALUES ('Frontend Engineer', 'Technology', '{"Frontend Developer", "Front End Engineer", "Front-End Developer", "Senior Frontend Engineer", "Senior Front-End Engineer", "Frontend Engineer", "React Front End Developer", "UI/UX Front End Developer", "Front-End Software Engineer", "Application Support Engineer"}', 'recMKjyrOZy99Au7F') ON CONFLICT (name) DO NOTHING;
INSERT INTO job_roles (name, family, synonyms, airtable_id) VALUES ('Frontend/Backend/Full‑stack Engineer', 'Technology', '{"Full Stack Developer", "Backend Developer", "Frontend Developer", "Full Stack Engineer", "Backend Engineer", "Frontend Engineer"}', 'recV8FtHyoT1vExFG') ON CONFLICT (name) DO NOTHING;
INSERT INTO job_roles (name, family, synonyms, airtable_id) VALUES ('Full‑stack Engineer', 'Technology', '{"Full Stack Developer", "Full Stack Engineer", "Software Engineer", "Full Stack Web Developer", "Web Developer", "Application Developer", "Software Developer", "Senior Full Stack Engineer"}', 'rec6U4s1RVtBEBdfQ') ON CONFLICT (name) DO NOTHING;
INSERT INTO job_roles (name, family, synonyms, airtable_id) VALUES ('GRC Analyst', 'Technology', '{"GRC Analyst", "IT GRC Analyst", "Senior Analyst IT GRC Security Risk", "GRC Consultant", "InfoSec GRC Consultant", "GRC Specialist", "GRC Associate", "IT Compliance Analyst", "Cybersecurity GRC Analyst", "SAP GRC Consultant"}', 'rec4GuPvX338HpWwL') ON CONFLICT (name) DO NOTHING;
INSERT INTO job_roles (name, family, synonyms, airtable_id) VALUES ('IAM Engineer', 'Technology', '{"IAM Engineer", "Identity and Access Management Engineer", "IAM Specialist", "IAM Consultant", "IAM Analyst", "Identity Management Engineer", "Identity Access Engineer", "Identity and Access Management Specialist", "Identity and Access Management Consultant"}', 'recxXinw3Pi1ErzR3') ON CONFLICT (name) DO NOTHING;
INSERT INTO job_roles (name, family, synonyms, airtable_id) VALUES ('ML Engineer', 'Technology', '{"Machine Learning Engineer", "ML Engineer", "AI/ML Engineer", "AI Engineer", "Machine Learning Specialist", "AI Specialist", "Deep Learning Engineer", "ML Ops Engineer", "AI/ML Platform Architect", "Principal ML Engineer"}', 'recGPLfdJBHoag0oY') ON CONFLICT (name) DO NOTHING;
INSERT INTO job_roles (name, family, synonyms, airtable_id) VALUES ('MLOps/DS Ops', 'Technology', '{"MLOps Engineer", "Senior MLOps Engineer", "AI Infrastructure Engineer", "ML Platform Engineer", "Machine Learning Operations Specialist", "Data Scientist – MLOps", "DevOps MLOps Engineer", "AI/ML Engineer", "AI Solutions Engineer"}', 'rec8QUbWCphUe95MG') ON CONFLICT (name) DO NOTHING;
INSERT INTO job_roles (name, family, synonyms, airtable_id) VALUES ('Mobile Dev', 'Technology', '{"Mobile Application Developer", "Mobile App Developer", "Mobile Developer", "Mobile Software Engineer", "Android Developer", "iOS Developer", "Senior Mobile Developer", "Lead Mobile Developer"}', 'rec8fJhzXnc2SUU0q') ON CONFLICT (name) DO NOTHING;
INSERT INTO job_roles (name, family, synonyms, airtable_id) VALUES ('NLP/CV Jr.', 'Technology', '{"Data Scientist", "NLP Engineer", "Computer Vision Engineer", "AI Engineer", "Machine Learning Engineer", "NLP Research Scientist", "Computer Vision Researcher", "AI Developer", "Research Assistant", "Data Engineer"}', 'rec8f3CrmCvUntwzD') ON CONFLICT (name) DO NOTHING;
INSERT INTO job_roles (name, family, synonyms, airtable_id) VALUES ('Network Engineer', 'Technology', '{"Network Engineer", "Network Security Engineer", "Senior Network Engineer", "IT Network Engineer", "Network Administrator", "Network Architect", "Network Support Engineer", "Network Operations Engineer", "Network Infrastructure Engineer", "Network Manager"}', 'rec4kQpdTuqn75aMl') ON CONFLICT (name) DO NOTHING;
INSERT INTO job_roles (name, family, synonyms, airtable_id) VALUES ('QA/Automation', 'Technology', '{"QA Automation Engineer", "QA Engineer", "Automation Test Engineer", "QA Automation Manager", "Lead QA Automation Engineer", "Senior QA Automation Engineer", "Automation Tester", "Quality Assurance Automation Engineer", "Automation QA Engineer", "QA Manual and Automation Tester"}', 'recYlcaUB96CfmiZZ') ON CONFLICT (name) DO NOTHING;
INSERT INTO job_roles (name, family, synonyms, airtable_id) VALUES ('Robotics Tech', 'Technology', '{"Robotics Engineer", "Robotics Technician", "Robotics Design Engineer", "Robotics Trainer", "STEM Robotics Instructor", "Robotics Automation Engineer", "Robotics Lab Supervisor", "Robotics Product Manager"}', 'recRay1HzoBkmqD4J') ON CONFLICT (name) DO NOTHING;
INSERT INTO job_roles (name, family, synonyms, airtable_id) VALUES ('SOC Analyst', 'Technology', '{"SOC Analyst", "Security Operations Center Analyst", "SOC L1 Analyst", "SOC L2 Analyst", "SOC L3 Analyst", "Security Analyst", "Cyber Security Analyst", "Cyber Threat Intelligence Analyst"}', 'recJmrOVVG7juztMu') ON CONFLICT (name) DO NOTHING;
INSERT INTO job_roles (name, family, synonyms, airtable_id) VALUES ('SRE (junior)', 'Technology', '{"Site Reliability Engineer", "SRE Engineer", "Junior Site Reliability Engineer", "Junior SRE", "DevOps Engineer", "Junior DevOps Engineer"}', 'recMxZDTlS5uRlbs8') ON CONFLICT (name) DO NOTHING;
INSERT INTO job_roles (name, family, synonyms, airtable_id) VALUES ('Security Analyst', 'Technology', '{"Security Analyst", "Information Security Analyst", "Cyber Security Analyst", "SOC Analyst", "Security Operations Center Analyst", "Cybersecurity Analyst", "IT Security Analyst", "Security Specialist", "Security Engineer", "Security Consultant"}', 'recheJgfnYvC4yDBe') ON CONFLICT (name) DO NOTHING;
INSERT INTO job_roles (name, family, synonyms, airtable_id) VALUES ('Technical PM', 'Technology', '{"Technical Project Manager", "Technical Program Manager", "IT Project Manager", "Technical Product Manager", "Project Manager", "Operations Manager (Projects & Technical)", "SAP Service Delivery Manager", "Technical Product Engineering Manager"}', 'recvLdB7B3MMAuxCa') ON CONFLICT (name) DO NOTHING;

-- Total: 84 roles, 791 synonyms
-- Family breakdown: Core Engineering=7, Management=38, Others=17, Technology=22